### ISSUE TITLE
Unable to display maps in IE

### ISSUE THREAD

**Issue by nagappan** [allenhwkim/angularjs-google-maps#126]
I have no issues opening ngmap.github.io, but when I place the example code from the plunker into my web site, it doesn't work, I could not figure out the reason.

Trying it on Windows 8.1 with IE 11. https://www.needsuggestion.com/test.html

NOTE: It works with Chrome on Mac and Safari on iOS/Mac.

If you need additional info, please let me know. Thanks for your help.

**Comment by nagappan** [comment]
Verified, things are working fine. Thanks

**Comment by allenhwkim** [comment]
No problem. Giving this repo. a star would help others as recommendation. :)

**Comment by nagappan** [comment]
Done :-)

**Comment by zsitro** [comment]
I still faced this issue with map height. quick fix was `map{height: auto !important}` because I specify dimensions with top/left/bottom/right css props anyway.
