### ISSUE TITLE
Google Maps Memory Leak When DOM is Recreated

### ISSUE THREAD

**Issue by lazamar** [allenhwkim/angularjs-google-maps#419]
There is a big memory leak going on. Every time the map is hidden or taken out of the DOM it does not get garbage collected and creates a leak of more than 3MB. In applications that stay in the same page for long, such as a hybrid mobile app, this causes a certain crash.

I created a codepen where you can hide and show the map. Take heap snapshots after toggling it a couple times to see the effect. 
http://codepen.io/lazamar/pen/OMLOxe

![Growing memory usage](https://cloud.githubusercontent.com/assets/11493705/11535373/86c6e92e-990b-11e5-97d5-4c8dac253b5b.png)

You can also see that even with a garbage collection that happens in the middle of this timeline the number of listeners and DOM nodes continues to increase.

![Growing number of listeners](https://cloud.githubusercontent.com/assets/11493705/11535387/9683e6a0-990b-11e5-8e6a-bd22fcb7807c.png)

**Comment by allenhwkim** [comment]
This is a known issue with Google maps. Let me see if we can make use of the existing instances without creating a new google map every single time when DOM is created.

**Comment by allenhwkim** [comment]
![image](https://cloud.githubusercontent.com/assets/1437734/11911272/5459e43e-a5de-11e5-976f-2ca6d1cad933.png)

This is fixed with 1.15.5 release. You can test it with https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/ui-router.html#/foo

**Comment by Nikitikitavi** [comment]
Issue still exist. https://www.screencast.com/t/nruUlmkuhB
I checked your example -  https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/ui-router.html#/foo and it still cause a memory leak. Can you check it pls?

**Comment by facetious** [comment]
<img width="1717" alt="screen shot 2018-12-17 at 5 10 42 pm" src="https://user-images.githubusercontent.com/1058563/50118752-b75b5000-021e-11e9-9626-d15f2c678ca8.png">
