### ISSUE TITLE
Weird custom markers position when zoom in  and out

### ISSUE THREAD

**Issue by oatto** [allenhwkim/angularjs-google-maps#451]
When make a zoom-change the custom markers position will move to wrong positions before they get back to the right positions.

**Comment by allenhwkim** [comment]
@oatto thanks for reporting this. This has been fixed and released with v1.16.1

**Comment by oatto** [comment]
Thank you for the fix. I like your library because it is light and easy to use, cheers !

**Comment by oatto** [comment]
Hi Kim,

It seems that on PC it is fine but when I test on mobile it move faster but still wrong before right.

**Comment by allenhwkim** [comment]
try again please. v 1.16.2

**Comment by oatto** [comment]
Finally.. Thanks !
