### ISSUE TITLE
(bug)  Map not initialize after route change since it is already Idle

### ISSUE THREAD

**Issue by trainerbill** [allenhwkim/angularjs-google-maps#466]
Using UI router if I switch state the mapController is removed but the map still exists in an idle state.  So when I go back to the previous state the new map is not initialized because it is already idle:

https://github.com/allenhwkim/angularjs-google-maps/blob/master/controllers/map-controller.js#L196

So NgMap.getMap.then() returns a could not find map since it is never added.  

One thing that I want to do for a v2 of this module is to make the maps persistant.  Instead of removing them on destroy allow like 5 or so maps to exist before removing.  So if you go back your map is in the same state it was in when you left.  As long as the map ID is the same then just return the existing map instead of recreating them all the time.

**Comment by allenhwkim** [comment]
Could you add an example with this error? It seems like a bug for me.

**Comment by thenikso** [comment]
I am experiencing probably this same issue. It goes away with `v1.13.14` so for the time being I'm reverting to that one

**Comment by trainerbill** [comment]
http://plnkr.co/edit/k26LNCGUw0AqVJULc8Wg?p=preview

GetMap is only alerted the first time.  The issue with this is that if I go to a new state and the map is returned to the pool if I call the map back out of the pool with the same coordinates it is "idle" and never intiated.

**Comment by simonh1000** [comment]
I have the same issue - when I switch route the page loads, but there are problems with the marker on the one map, and the heatmap on the other. I guess that is getMap not being called

**Comment by allenhwkim** [comment]
fixed it with 1.16.7

**Comment by simonh1000** [comment]
Should I have to do something in particular to get a smooth experience, like 'unload' the map when the router view is changed, because it still does not seem to work for me

**Comment by allenhwkim** [comment]
@simonh1000 I made a fix to fire map idle event with 100ms delay. I hope this works for you.

**Comment by roshaw** [comment]
Currently it's working for me with 

`<ng-map id="mapId">

NgMap.getMap({id: 'mapID'}).then(function(map) {}`

**Comment by NicolasBonduel** [comment]
Hello,

I have the same issue.
The getMap function is called in a `$http.get(//).then(function(//) {` in my case because I need to render stuff from an API.

**Comment by whisher** [comment]
Hello,
I have the same issue.
At the top of a ui.router controller
```javascript
NgMap.getMap('mapID').then(function(map) {
    console.log('map success', map);
    apartments.map = map;
  }).catch(function(map){
    console.log('map error', map);
  });
```
I've got
*map error could not find map*
:(
